import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/sceneone/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <nav className={styles.navbar}>
          <div>
            <Link href="/">
              <a>
                <span className={styles.titulo}>ALKIMERA DEMOS XR</span>
              </a>
            </Link>
          </div>
          <div className={styles.sitealkimera}>
            <span>© 2022 Made from</span>
            <Link href="https:// alkimera.tech">
              <a> Alkimera Tech</a>
            </Link>
          </div>
        </nav>
        <div>
          <section>
            <h1>Demonstrações XR Alkimera Tecnologia</h1>
            <div className={styles.contentscenes}>
              <h2>Demos:</h2>
              <div>
                <ul className={styles.boxcards}>
                  <li className={styles.cardscenes}>
                    <Link href="/sceneone">
                    <a>
                      <p>Scene One</p>
                      <Image src="/sceneone.png" alt="Scene One" width={300} height={300} />
                    </a>
                    </Link>
                  </li>
                  <li className={styles.cardscenes}>
                    <Link href="/sceneone">
                    <a>
                      <p>Scene One</p>
                      <Image src="/sceneone.png" alt="Scene One" width={300} height={300} />
                    </a>
                    </Link>
                  </li>
                  <li className={styles.cardscenes}>
                    <Link href="/sceneone">
                    <a>
                      <p>Scene One</p>
                      <Image src="/sceneone.png" alt="Scene One" width={300} height={300} />
                    </a>
                    </Link>
                  </li>
                  <li className={styles.cardscenes}>
                    <Link href="/sceneone">
                    <a>
                      <p>Scene One</p>
                      <Image src="/sceneone.png" alt="Scene One" width={300} height={300} />
                    </a>
                    </Link>
                  </li>
                  <li className={styles.cardscenes}>
                    <Link href="/sceneone">
                    <a>
                      <p>Scene One</p>
                      <Image src="/sceneone.png" alt="Scene One" width={300} height={300} />
                    </a>
                    </Link>
                  </li>
                  <li className={styles.cardscenes}>
                    <Link href="/sceneone">
                    <a>
                      <p>Scene One</p>
                      <Image src="/sceneone.png" alt="Scene One" width={300} height={300} />
                    </a>
                    </Link>
                  </li>
                  
                </ul>
              </div>
            </div>
          </section>
        </div>

      </main>
    </div>
  )
}

