import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/sceneone/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <nav className={styles.navbar}>
          <div>
            <a href="/">
              <span className={styles.titulo}>ALKIMERA DEMOS XR</span>
            </a>
          </div>
          <div className={styles.sitealkimera}>
            <span>© 2022 Made from</span>
            <a href="https:// alkimera.tech"> Alkimera Tech</a>
          </div>
        </nav>
        <div>
          <section>
            <h1>Demonstrações XR Alkimera Tecnologia</h1>
            <div className={styles.contentscenes}>
              <h2>Demos:</h2>
              <div>
                <ul className={styles.boxcards}>
                  <li className={styles.cardscenes}>
                    <a href="/sceneone">
                      <p>Scene One</p>
                      <img width={240} src="/sceneone.png" alt="" />
                    </a>
                  </li>
                  <li className={styles.cardscenes}>
                    <a href="/sceneone">
                      <p>Scene Two</p>
                      <img width={240} src="/sceneone.png" alt="" />
                    </a>
                  </li>
                  <li className={styles.cardscenes}>
                    <a href="/sceneone">
                      <p>Scene Three</p>
                      <img width={240} src="/sceneone.png" alt="" />
                    </a>
                  </li>
                  <li className={styles.cardscenes}>
                    <a href="/sceneone">
                      <p>Scene Four</p>
                      <img width={240} src="/sceneone.png" alt="" />
                    </a>
                  </li>
                  <li className={styles.cardscenes}>
                    <a href="/sceneone">
                      <p>Scene Five</p>
                      <img width={240} src="/sceneone.png" alt="" />
                    </a>
                  </li>
                  <li className={styles.cardscenes}>
                    <a href="/sceneone">
                      <p>Scene Six</p>
                      <img width={240} src="/sceneone.png" alt="" />
                    </a>
                  </li>
                  <li className={styles.cardscenes}>
                    <a href="/sceneone">
                      <p>Scene Seven</p>
                      <img width={240} src="/sceneone.png" alt="" />
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </section>
        </div>

      </main>
    </div>
  )
}

